version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5174:5174"
    depends_on:
      - backend
    networks:
      - xiangqi-network

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - xiangqi-network

networks:
  xiangqi-network:
    driver: bridge